### ISSUE TITLE
Use more appropriate Salts states to better handle execution of inspector install script

### ISSUE THREAD

**Issue by eemperor** [plus3it/amazon-inspector-formula#5]
Address PR review comment below:

https://github.com/plus3it/amazon-inspector-formula/pull/4#pullrequestreview-258562683

>This is fine to get us unblocked, but we can take a couple new issues:
>*    Run the install script whenever its hash changes (use `file.managed`)
>*    Eliminate `cmd.run` usage where there are appropriate/equivalent salt states (use `file.replace` and `service.running`)

**Comment by ferricoxide** [comment]
Closing: our oganization's use of [Inspector v1](https://docs.aws.amazon.com/inspector/v1/userguide/inspector_introduction.html) content has been deprecated in favor of Inspector v2.
